Replace $NETKIT_HOME

diff --git a/bin/lclean.in b/bin/lclean.in
--- a/bin/lclean.in
+++ b/bin/lclean.in
@@ -18,15 +18,14 @@
 #     You should have received a copy of the GNU General Public License
 #     along with Netkit.  If not, see <http://www.gnu.org/licenses/>.
 
-# This script displays information about a lab without running it. Optionally,
-# it can create a PostScript file containing the level 2 topology of the lab.
+# This script can be used to clean up a directory that contains a Netkit lab.
+# All temporary files are removed, including .disk files.
 
 SCRIPTNAME=`basename $0`
 
 # The following line has been introduced to ensure backward compatibility
-: ${NETKIT_HOME:=$VLAB_HOME}
 
-if [ -z "$NETKIT_HOME" ]; then
+if [ ! 0 ]; then
    echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not properly set;"
    echo 1>&2 "please set it as described in the Netkit documentation and try"
    echo 1>&2 "again."
@@ -35,52 +34,67 @@ fi
 
 CMDLINE="$0 $*"
 
-. "$NETKIT_HOME/bin/script_utils"
+. "[@]netkitdir[@]/bin/script_utils"
 
 
 # Write to the vcommands log
 logWrite $0 $*
 
 
-# This function is used to print the lhalt usage
+# This function is used to print the lclean usage
 help() {
    echo
-   echo "Usage: $SCRIPTNAME [options]"
+   echo "Usage: $SCRIPTNAME [options] [MACHINE-NAME] ..."
    cat << END_OF_HELP
 
-This command displays information about a Netkit lab without running it.
-Displayed information includes the number of virtual machines that make up the
-lab. If asked to, the command can create a PostScript file containing a
-graphical map of the link-level topology of the lab.
+This command can be used to clean up a directory containing a Netkit lab. It
+takes care of removing any temporary files, that is, '.ready' files, '.log'
+files, the 'readyfor.test' file as well as virtual machines (COW) filesystems
+('.disk' files). Therefore, any change to the virtual machines filesystems is
+lost. Of course, any persistent part of the lab is preserved, including those
+files that are automatically copied inside virtual machines during the boot
+phase.
+
 Available options are:
 
-  -d DIRECTORY        Assume the lab is located inside DIRECTORY. By default,
-                      the lab is assumed to be located in the current directory.
-  -m, --map=FILE      Create a graphical link-level topology map of the lab and
-                      save it into FILE in PostScript format. This requires the
-                      Graphviz library to be installed.
+  -d DIRECTORY        Clean up the lab inside DIRECTORY. By default, the
+                      cleaning process takes place in the current directory.
 
-Other standard options are:
+This command also supports the following standard options:
 
   -h, --help          Show this help.
+  -v, --verbose       Show which files are being deleted.
       --version       Print version information and exit.
+
+The cleaning process involves temporary files generated for any of the virtual
+machines of the lab. If one or more MACHINE-NAMEs are passed on the command
+line, then only those files generated for the matching virtual machines are
+deleted, as well as the 'readyfor.test' file. If any of the MACHINE-NAMEs is
+invalid (i.e., it does not correspond to a virtual machine of the lab), it will
+simply be skipped.
 
 END_OF_HELP
 }
 
 
+# This function checks whether its argument contains spaces
+checkSpaces() {
+   if echo "$1" | grep -q " "; then
+      warning "$SCRIPTNAME" "$CMDLINE" "$0" \
+              "Argument \"$1\" contains spaces. They are not allowed."
+      exit 1
+   fi
+}
+
+
 # Get command line options
 INVALID_OPTION=0
-OPT_LIST="help,version,map:"
-CMDLINE_OPTIONS=`getopt -ql "$OPT_LIST" -- "hd:m:" "$@"`
+OPT_LIST="help,version,verbose"
+CMDLINE_OPTIONS=`getopt -ql "$OPT_LIST" -- "hd:v" "$@"`
 if [ $? -gt 0 ]; then
    INVALID_OPTION=1
 fi
 
-
-# Using verbose mode tells vcrash to wait for virtual machines to stop before
-# returning.
-VERBOSE=1
 
 # Parse command line options
 parseCmdLine() {
@@ -101,11 +115,9 @@ parseCmdLine() {
             help
             exit;;
             
-         --map|-m)
-            shift; CURRENT_ARGUMENT="$1"
-            checkSpaces "$CURRENT_ARGUMENT"
-            MAP_FILE="$CURRENT_ARGUMENT";;
-            
+         --verbose|-v)
+            VERBOSE=1;;
+         
          --version)
             showVersion
             exit 0;;
@@ -117,10 +129,11 @@ parseCmdLine() {
       shift
    done
    
-   if [ $# -gt 0 ]; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option: \"$1\"."
-      exit 1
-   fi
+   while [ $# -gt 0 ]; do
+      checkSpaces "$1"
+      VHOSTLIST="$VHOSTLIST $1"
+      shift
+   done
 }
 eval parseCmdLine $CMDLINE_OPTIONS
 
@@ -133,7 +146,7 @@ fi
 
 # If no lab directory has been given, assume current directory
 LAB_DIRECTORY=${LAB_DIRECTORY:-${PWD}}
-. "$NETKIT_HOME/bin/lcommon"
+. "[@]netkitdir[@]/bin/lcommon"
 
 # Check that the lab directory exists
 if [ ! -d "$LAB_DIRECTORY" ]; then
@@ -151,24 +164,14 @@ fi
 
 # Print some information about the lab
 echo
-becho "====================== Lab information =========================="
+becho "====================== Cleaning up lab =========================="
 labWelcome
-echo
-buildAffectedVHostList
-becho "The lab is made up of `echo $LABHOSTS | awk '{print NF}'` virtual machines ($LABHOSTS)."
-if [ -f "$LAB_DIRECTORY/lab.dep" ]; then
-   becho "The lab supports parallel startup."
-fi
+becho "================================================================="
 
-if [ ! -z "$MAP_FILE" ]; then
-   if [ ! -f "$LAB_DIRECTORY/lab.conf" ]; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" "Unable to find file lab.conf: cannot create topology map."
-      exit 1
-   fi
-   if labMap "$MAP_FILE"; then
-      becho "Link-level topology map saved into $MAP_FILE."
-   fi
-fi
+# Clean up the lab directory
+labClean
+echo
+becho "Cleaning completed."
 becho "================================================================="
 
 echo
diff --git a/check_configuration.d/02-check_environment.sh.in b/check_configuration.d/02-check_environment.sh.in
--- a/check_configuration.d/02-check_environment.sh.in
+++ b/check_configuration.d/02-check_environment.sh.in
@@ -28,31 +28,45 @@
 # you should call one of the functions "check_warning" or "check_failure"
 # (depending on the severity of the problem).
 
-# Check whether Netkit man pages are reachable
+# Check whether NETKIT_HOME has been set
 
-check_message "Checking for availability of man pages... "
+check_message "Checking environment... "
 
-if ! echo "${MANPATH}" | grep -qE "(:$NETKIT_HOME\/man\/?$)|(^$NETKIT_HOME\/man\/?:)|(:$NETKIT_HOME\/man\/?:)"; then
+if [ ! 0 ]; then
    echo "failed!"
    echo
-   if [ -z "$MANPATH" ]; then
-      NEW_MANPATH=":${NETKIT_HOME%/}/man"
-   else
-      NEW_MANPATH="\$MANPATH::${NETKIT_HOME%/}/man"
-   fi
-   echo "*** Warning: the environment variable MANPATH is not properly set. This"
-   echo "will make man pages inaccessible. You should set it to the following"
-   echo "value (all colons must be included):"
+   echo "*** Error: the environment variable NETKIT_HOME is not set. You should"
+   echo "set it to the following value:"
    echo
-   echo $NEW_MANPATH
+   echo $PWD
    echo
    echo "You can use one of the following commands, depending on the shell you"
    echo "are using:"
    echo
-   echo "(for bash) export MANPATH=$NEW_MANPATH"
-   echo "(for csh)  setenv MANPATH $NEW_MANPATH"
+   echo "(for bash) export NETKIT_HOME=$PWD"
+   echo "(for csh)  setenv NETKIT_HOME $PWD"
    echo
-   check_warning
+   check_failure
 else
-   echo "passed."
+   if [ "[@]netkitdir[@]" != "$PWD" -a "[@]netkitdir[@]" != "${PWD}/" ]; then
+      echo "failed!"
+      echo
+      echo "*** Error: the environment variable NETKIT_HOME currently points at the"
+      echo "wrong directory:"
+      echo
+      echo "(current value) [@]netkitdir[@]"
+      echo "(should be)     $PWD"
+      echo
+      echo "In order to fix this, you can use one of the following commands, depending"
+      echo "on the shell you are using:"
+      echo
+      echo "(for bash) export NETKIT_HOME=$PWD"
+      echo "(for csh)  setenv NETKIT_HOME $PWD"
+      echo
+      check_failure
+   else
+      echo "passed."
+   fi
 fi
+
+NETKIT_BIN_DIR=[@]netkitdir[@]/bin
